/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pengelolaanangkakredit;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author reyha
 */
public class DialogKelolaKredit extends javax.swing.JDialog {

    Connection con = DatabaseConnectivity.getConnection();
    String nip;

    /**
     * Creates new form DialogKelolaKredit
     */
    public DialogKelolaKredit(java.awt.Frame parent, boolean modal) {

    }

    DialogKelolaKredit(FormPejabatFungsionalNonPeneliti aThis, boolean b, Object valueAt, Object valueAt0, Object valueAt1, Object valueAt2, Object valueAt3) {
        super(aThis, b);
        initComponents();
        setLocationRelativeTo(this);
        labelNama.setText((String) valueAt);
        labelNIP.setText((String) valueAt0);
        labelBagian.setText((String) valueAt1);
        labelBidang.setText((String) valueAt2);
        labelGol.setText((String) valueAt3);
        this.nip = (String) valueAt0;

        try {
            String sql = "select * from jab_fung where nip='" + valueAt0 + "'";
            java.sql.Statement stat = con.createStatement();
            java.sql.ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()) {
                fieldUnsurUtama.setText(hasil.getString(9));
                fieldPendidikanFormal.setText(hasil.getString(10));
                fieldUnsurUtamaIjazah.setText(hasil.getString(11));
                fieldUnsurPenunjang.setText(hasil.getString(12));
                labelJabatan.setText(hasil.getString(7));
                java.util.Date dateTMTGol = new SimpleDateFormat("yyyy-MM-dd").parse(hasil.getString(6));
                fieldTMTGol.setDate(dateTMTGol);
                java.util.Date dateTMTJabatan = new SimpleDateFormat("yyyy-MM-dd").parse(hasil.getString(8));
                fieldTMTJabatan.setDate(dateTMTJabatan);
                java.util.Date dateAwal = new SimpleDateFormat("yyyy-MM-dd").parse(hasil.getString(13));
                fieldAwal.setDate(dateAwal);
                java.util.Date dateAkhir = new SimpleDateFormat("yyyy-MM-dd").parse(hasil.getString(14));
                fieldAkhir.setDate(dateAkhir);
                fieldLamanyaAngkaKredit.setText(hasil.getString(15));
                fieldJumlahAngkaKredit.setText(hasil.getString(16));
                fieldNilaiYangDibutuhkan.setText(hasil.getString(17));
                fieldNilaiYangDibutuhkanIjazah.setText(hasil.getString(18));
                fieldSisa.setText(hasil.getString(19));
                fieldNilaiUtamaDibutuhkan.setText(hasil.getString(20));
                fieldNilaiPenunjangDibutuhkan.setText(hasil.getString(21));
                fieldGolongan.setText(hasil.getString(22));
                fieldJabatan.setText(hasil.getString(23));
                fieldKeterangan.setText(hasil.getString(24));
            }
        } catch (Exception e) {
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        labelNama = new javax.swing.JLabel();
        labelNIP = new javax.swing.JLabel();
        labelBagian = new javax.swing.JLabel();
        labelBidang = new javax.swing.JLabel();
        labelGol = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        fieldTMTJabatan = new com.toedter.calendar.JDateChooser();
        fieldUnsurUtama = new javax.swing.JTextField();
        fieldPendidikanFormal = new javax.swing.JTextField();
        fieldUnsurUtamaIjazah = new javax.swing.JTextField();
        fieldUnsurPenunjang = new javax.swing.JTextField();
        fieldAwal = new com.toedter.calendar.JDateChooser();
        fieldAkhir = new com.toedter.calendar.JDateChooser();
        fieldLamanyaAngkaKredit = new javax.swing.JTextField();
        fieldJumlahAngkaKredit = new javax.swing.JTextField();
        fieldNilaiYangDibutuhkan = new javax.swing.JTextField();
        fieldNilaiYangDibutuhkanIjazah = new javax.swing.JTextField();
        fieldSisa = new javax.swing.JTextField();
        fieldNilaiUtamaDibutuhkan = new javax.swing.JTextField();
        fieldNilaiPenunjangDibutuhkan = new javax.swing.JTextField();
        fieldGolongan = new javax.swing.JTextField();
        fieldJabatan = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        fieldKeterangan = new javax.swing.JTextArea();
        fieldTMTGol = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        labelJabatan = new javax.swing.JLabel();
        buttonSimpan = new javax.swing.JButton();
        buttonHapus = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Nama  :");

        jLabel2.setText("NIP      :");

        jLabel3.setText("Bagian :");

        jLabel4.setText("Bidang :");

        jLabel5.setText("Gol      :");

        labelNama.setText("labelNama");

        labelNIP.setText("labelNIP");

        labelBagian.setText("labelBagian");

        labelBidang.setText("labelBidang");

        labelGol.setText("labelGol");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Form Kelola Kredit"));

        jLabel6.setText("TMT Gol");

        jLabel8.setText("TMT Jabatan");

        jLabel9.setText("Unsur Utama");

        jLabel10.setText("Pendidikan Formal");

        jLabel11.setText("Unsur Utama - Ijazah");

        jLabel12.setText("Unsur Penunjang");

        jLabel13.setText("Masa Penilaian Awal");

        jLabel14.setText("Masa Penilaian Akhir");

        jLabel15.setText("Lamanya Angka Kredit");

        jLabel16.setText("Jumlah Angka Kredit");

        jLabel17.setText("Nilai yang Dibutuhkan");

        jLabel18.setText("Nilai yang Dibutuhkan - Ijazah");

        jLabel19.setText("Sisa");

        jLabel20.setText("Nilai Utama yang Dibutuhkan");

        jLabel21.setText("Nilai Penunjang yang Dibutuhkan");

        jLabel22.setText("Akan Naik ke Golongan");

        jLabel23.setText("Akan Naik ke Jabatan");

        jLabel24.setText("Keterangan");

        fieldLamanyaAngkaKredit.setEditable(false);

        fieldJumlahAngkaKredit.setEditable(false);
        fieldJumlahAngkaKredit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldJumlahAngkaKreditActionPerformed(evt);
            }
        });

        fieldNilaiYangDibutuhkan.setEditable(false);
        fieldNilaiYangDibutuhkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNilaiYangDibutuhkanActionPerformed(evt);
            }
        });

        fieldNilaiYangDibutuhkanIjazah.setEditable(false);

        fieldSisa.setEditable(false);

        fieldNilaiUtamaDibutuhkan.setEditable(false);

        fieldNilaiPenunjangDibutuhkan.setEditable(false);

        fieldGolongan.setEditable(false);

        fieldJabatan.setEditable(false);

        fieldKeterangan.setColumns(20);
        fieldKeterangan.setRows(3);
        jScrollPane1.setViewportView(fieldKeterangan);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addGap(62, 62, 62)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 148, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(fieldTMTJabatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(fieldAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(14, 14, 14)))
                                .addGap(123, 123, 123))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(fieldUnsurUtamaIjazah, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fieldUnsurPenunjang)
                                    .addComponent(fieldPendidikanFormal))
                                .addContainerGap())
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(fieldUnsurUtama, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel20))
                                .addGap(22, 22, 22)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fieldJumlahAngkaKredit)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(fieldAwal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(fieldNilaiYangDibutuhkan)
                                    .addComponent(fieldNilaiYangDibutuhkanIjazah)
                                    .addComponent(fieldSisa)
                                    .addComponent(fieldNilaiUtamaDibutuhkan)
                                    .addComponent(fieldLamanyaAngkaKredit)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel6))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(55, 55, 55)
                                        .addComponent(fieldTMTGol, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel8)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(56, 56, 56)
                                        .addComponent(fieldGolongan))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(56, 56, 56)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(fieldJabatan)
                                            .addComponent(jScrollPane1)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addGap(8, 8, 8)
                                .addComponent(fieldNilaiPenunjangDibutuhkan))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8)
                    .addComponent(fieldTMTJabatan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fieldTMTGol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(fieldUnsurUtama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(fieldPendidikanFormal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(fieldUnsurUtamaIjazah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(fieldUnsurPenunjang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fieldAwal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fieldAkhir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(fieldLamanyaAngkaKredit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(fieldJumlahAngkaKredit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(fieldNilaiYangDibutuhkan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(fieldNilaiYangDibutuhkanIjazah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(fieldSisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(fieldNilaiUtamaDibutuhkan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(fieldNilaiPenunjangDibutuhkan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(fieldGolongan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(fieldJabatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jLabel7.setText("Jabatan     :");

        labelJabatan.setText("labelJabatan");

        buttonSimpan.setText("Simpan");
        buttonSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSimpanActionPerformed(evt);
            }
        });

        buttonHapus.setText("Hapus");
        buttonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHapusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelBidang)
                            .addComponent(labelGol)
                            .addComponent(labelJabatan)
                            .addComponent(labelBagian)
                            .addComponent(labelNama))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelNIP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonHapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonSimpan)
                        .addGap(23, 23, 23))))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(labelNama))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(labelNIP)
                    .addComponent(buttonSimpan)
                    .addComponent(buttonHapus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(labelBagian))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(labelBidang))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(labelGol))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(labelJabatan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fieldJumlahAngkaKreditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldJumlahAngkaKreditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldJumlahAngkaKreditActionPerformed

    private void fieldNilaiYangDibutuhkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNilaiYangDibutuhkanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNilaiYangDibutuhkanActionPerformed

    private void buttonSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSimpanActionPerformed
        // TODO add your handling code here:
        java.util.Date TMTGol = (java.util.Date) fieldTMTGol.getDate();
        java.util.Date TMTJabatan = (java.util.Date) fieldTMTJabatan.getDate();
        Date ys = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        SimpleDateFormat s = new SimpleDateFormat("dd MMMM yyyy");
        DateFormat dateFormat = new SimpleDateFormat("dd MMMM yyyy");
        DecimalFormat decimalFormat2 = new DecimalFormat("#.##");
        DecimalFormat decimalFormat4 = new DecimalFormat("#.####");
        double lamanya_angka_kredit = 0;
        try {
            Date sekarang = dateFormat.parse(s.format(ys));
            Date tanggal_jabatan = dateFormat.parse(s.format(TMTJabatan));
            double sekarang_long = sekarang.getTime();
            double tanggal_jabatan_long = tanggal_jabatan.getTime();
            double diff = sekarang_long - tanggal_jabatan_long;
            double lama = diff / (24 * 60 * 60 * 1000);
            lamanya_angka_kredit = lama / 365;

        } catch (ParseException ex) {
            Logger.getLogger(DialogKelolaKredit.class.getName()).log(Level.SEVERE, null, ex);
        }
        double nilai_dibutuhkan = 0;
        double jumlah_angka_kredit = Double.parseDouble(fieldUnsurUtamaIjazah.getText()) + Double.parseDouble(fieldUnsurPenunjang.getText());
        if (labelGol.getText().equals("II/a")) {
            nilai_dibutuhkan = 40;
        } else if (fieldGolongan.getText().equals("II/b")) {
            nilai_dibutuhkan = 60;
        } else if (fieldGolongan.getText().equals("II/c")) {
            nilai_dibutuhkan = 80;
        } else if (fieldGolongan.getText().equals("II/d")) {
            nilai_dibutuhkan = 100;
        } else if (fieldGolongan.getText().equals("III/a")) {
            nilai_dibutuhkan = 150;
        } else if (fieldGolongan.getText().equals("III/b")) {
            nilai_dibutuhkan = 200;
        } else if (fieldGolongan.getText().equals("III/c")) {
            nilai_dibutuhkan = 300;
        } else if (fieldGolongan.getText().equals("III/d") || fieldGolongan.getText().equals("III/d M")) {
            nilai_dibutuhkan = 400;
        } else if (fieldGolongan.getText().equals("IV/a")) {
            nilai_dibutuhkan = 550;
        } else if (fieldGolongan.getText().equals("IV/b")) {
            nilai_dibutuhkan = 700;
        }

        double nilai_dibutuhkan_ijazah = nilai_dibutuhkan - Double.parseDouble(fieldPendidikanFormal.getText());

        double sisa = Math.abs(nilai_dibutuhkan_ijazah - jumlah_angka_kredit);
        double nilai_utama_dibutuhkan;
        if (nilai_dibutuhkan_ijazah * 80 / 100 - Double.parseDouble(fieldUnsurUtamaIjazah.getText()) <= 0) {
            nilai_utama_dibutuhkan = 0;
        } else {
            nilai_utama_dibutuhkan = nilai_dibutuhkan_ijazah * 80 / 100 - Double.parseDouble(fieldUnsurUtamaIjazah.getText());
        }

        double nilai_utama_dibutuhkan_penunjang;
        if (sisa - nilai_utama_dibutuhkan <= 0) {
            nilai_utama_dibutuhkan_penunjang = 0;
        } else {
            nilai_utama_dibutuhkan_penunjang = sisa - nilai_utama_dibutuhkan;
        }

        String jabatan = null;
//        if (labelGol.getText().equals("II/a") && labelBagian.getText().equals("Pengawas Radiasi")) {
//            jabatan = "PR P-Pemula";
//        } else if (labelGol.getText().equals("II/a") && labelBagian.getText().equals("Pranata Nuklir Terampil")) {
//            jabatan = "PN Muda";
//        } else if (labelGol.getText().equals("II/a") && labelBagian.getText().equals("Teknisi Litkayasa Pelaksana Pemula")) {
//            jabatan = "TL P-Pemula";
//        } else if (labelGol.getText().equals("II/a") && labelBagian.getText().equals("Pranata Humas")) {
//            jabatan = "PH Pelaksana Pemula";
//        } else if (labelGol.getText().equals("II/b") && labelBagian.getText().equals("Pengawas Radiasi")) {
//            jabatan = "PR Pelaksana";
//        } else if (labelGol.getText().equals("II/b") && labelBagian.getText().equals("Pranata Nuklir Terampil")) {
//            jabatan = "PN Pelaksana";
//        } else if (labelGol.getText().equals("II/b") && labelBagian.getText().equals("Teknisi Litkayasa Pelaksana Pemula")) {
//            jabatan = "PN Pelaksana";
//        } else if (labelGol.getText().equals("II/b") && labelBagian.getText().equals("Pustakawan")) {
//            jabatan = "P Pelaksana";
//        } else if (labelGol.getText().equals("II/b") && labelBagian.getText().equals("Arsiparis")) {
//            jabatan = "As. Arsiparis Madya";
//        } else if (labelGol.getText().equals("II/b") && labelBagian.getText().equals("Pranata Humas")) {
//            jabatan = "PH Pelaksana";
//        } else if (labelGol.getText().equals("II/c") && labelBagian.getText().equals("Pengawas Radiasi")) {
//            jabatan = "PR Pelaksana";
//        } else if (labelGol.getText().equals("II/c") && labelBagian.getText().equals("Pranata Nuklir Terampil")) {
//            jabatan = "PN Terampil";
//        } else if (labelGol.getText().equals("II/c") && labelBagian.getText().equals("Teknisi Litkayasa Pelaksana Pemula")) {
//            jabatan = "PN Pelaksana";
//        } else if (labelGol.getText().equals("II/c") && labelBagian.getText().equals("Pustakawan")) {
//            jabatan = "P Pelaksana";
//        } else if (labelGol.getText().equals("II/c") && labelBagian.getText().equals("Arsiparis")) {
//            jabatan = "As. Arsiparis";
//        } else if (labelGol.getText().equals("II/c") && labelBagian.getText().equals("Analis KEPEG.T")) {
//            jabatan = "AK Pelaksana";
//        } else if (labelGol.getText().equals("II/c") && labelBagian.getText().equals("Pranata Humas")) {
//            jabatan = "PH Pelaksana";
//        }
        
        String golongan = null;
        if (nilai_dibutuhkan == 40) {
            golongan = "II/b";
        } else if (nilai_dibutuhkan == 60) {
            golongan = "II/c";
        } else if (nilai_dibutuhkan == 80) {
            golongan = "II/d";
        } else if (nilai_dibutuhkan == 100) {
            golongan = "III/a";
        } else if (nilai_dibutuhkan == 150) {
            golongan = "III/b";
        } else if (nilai_dibutuhkan == 200) {
            golongan = "III/c";
        } else if (nilai_dibutuhkan == 300) {
            golongan = "III/d";
        } else if (nilai_dibutuhkan == 400) {
            golongan = "IV/a";
        } else if (nilai_dibutuhkan == 550) {
            golongan = "IV/b";
        } else if (nilai_dibutuhkan == 700) {
            golongan = "IV/c";
        }
        
        String keterangan = fieldKeterangan.getText();
        
        try {
                String sql = "update jab_fung set TMT_GOL=?,"
                        + " TMT_Jabatan=?,"
                        + " Unsur_Utama=?,"
                        + " Pendidikan_Formal_(Ijazah)=?,"
                        + " Unsur_Utama_(Minus_Ijazah)=?,"
                        + " Unsur_Penunjang=?,"
                        + " Masa_Penilaian_Awal=?,"
                        + " Masa_Penilaian_Akhir=?"
                        + " Lama=?,"
                        + " Jumlah_Angka_Kredit=?,"
                        + " Nilai_yang_Dibutuhkan=?,"
                        + " Nilai_yang_Dibutuhkan_(Minus_Ijazah)=?,"
                        + " Sisa=?,"
                        + " Utama=?,"
                        + " Penunjang=?,"
                        + " Akan_Naik_ke_Gol=?,"
                        + " Akan_Naik_ke_Jabatan=?,"
                        + " Keterangan=? where nip ='"+this.nip+"'";
                PreparedStatement stat = (PreparedStatement) con.prepareStatement(sql);
                stat.setDate(1, new java.sql.Date(TMTGol.getTime()));
                stat.setDate(2, new java.sql.Date(TMTJabatan.getTime()));
                stat.setString(3, fieldUnsurUtama.getText());
                stat.setString(4, fieldPendidikanFormal.getText());
                stat.setString(5, fieldUnsurUtamaIjazah.getText());
                stat.setString(6, fieldUnsurPenunjang.getText());
                stat.setString(7, sdf.format(fieldAwal.getDate()));
                stat.setString(8, sdf.format(fieldAkhir.getDate()));
                stat.setString(9, decimalFormat2.format(lamanya_angka_kredit));
                stat.setString(10, decimalFormat2.format(jumlah_angka_kredit));
                stat.setString(11, decimalFormat2.format(nilai_dibutuhkan));
                stat.setString(12, decimalFormat2.format(nilai_dibutuhkan_ijazah));
                stat.setString(13, decimalFormat2.format(sisa));
                stat.setString(14, decimalFormat2.format(nilai_utama_dibutuhkan));
                stat.setString(15, decimalFormat2.format(nilai_utama_dibutuhkan_penunjang));
                stat.setString(16, golongan);
                stat.setString(17, labelJabatan.getText());
                stat.setString(18, keterangan);
                System.out.println(new java.sql.Date(TMTGol.getTime()));
                System.out.println(new java.sql.Date(TMTJabatan.getTime()));
                System.out.println(fieldUnsurUtama.getText());
                System.out.println(fieldPendidikanFormal.getText());
                System.out.println(fieldUnsurUtamaIjazah.getText());
                System.out.println(fieldUnsurPenunjang.getText());
                System.out.println(sdf.format(fieldAwal.getDate()));
                System.out.println(sdf.format(fieldAkhir.getDate()));
                System.out.println(decimalFormat2.format(lamanya_angka_kredit));
                System.out.println(jumlah_angka_kredit);
                System.out.println(nilai_dibutuhkan);
                System.out.println(nilai_dibutuhkan_ijazah);
                System.out.println(decimalFormat2.format(sisa));
                System.out.println(decimalFormat2.format(nilai_utama_dibutuhkan));
                System.out.println(nilai_utama_dibutuhkan_penunjang);
                System.out.println(golongan);
                System.out.println(labelJabatan.getText());
                System.out.println(keterangan);
                
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "Menyimpan data BERHASIL!","Informasi", JOptionPane.INFORMATION_MESSAGE);
            }catch (SQLException | HeadlessException ex){
                JOptionPane.showMessageDialog(null, "Menyimpan data GAGAL!","Informasi", JOptionPane.INFORMATION_MESSAGE);
            }
    }//GEN-LAST:event_buttonSimpanActionPerformed

    private void buttonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHapusActionPerformed
        // TODO add your handling code here:
        int ok = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin ingin menghapus data dengan NIP : " + this.nip + "?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (ok == 0) {
            try {
                //panggil method koneksi
                String sql = "DELETE FROM jab_fung WHERE nip = '" + this.nip + "'";
                Statement st = con.createStatement();
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "Data Berhasil di hapus");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Data Gagal di hapus");
            }
            this.dispose();
        }
    }//GEN-LAST:event_buttonHapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogKelolaKredit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogKelolaKredit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogKelolaKredit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogKelolaKredit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogKelolaKredit dialog = new DialogKelolaKredit(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonHapus;
    private javax.swing.JButton buttonSimpan;
    private com.toedter.calendar.JDateChooser fieldAkhir;
    private com.toedter.calendar.JDateChooser fieldAwal;
    private javax.swing.JTextField fieldGolongan;
    private javax.swing.JTextField fieldJabatan;
    private javax.swing.JTextField fieldJumlahAngkaKredit;
    private javax.swing.JTextArea fieldKeterangan;
    private javax.swing.JTextField fieldLamanyaAngkaKredit;
    private javax.swing.JTextField fieldNilaiPenunjangDibutuhkan;
    private javax.swing.JTextField fieldNilaiUtamaDibutuhkan;
    private javax.swing.JTextField fieldNilaiYangDibutuhkan;
    private javax.swing.JTextField fieldNilaiYangDibutuhkanIjazah;
    private javax.swing.JTextField fieldPendidikanFormal;
    private javax.swing.JTextField fieldSisa;
    private com.toedter.calendar.JDateChooser fieldTMTGol;
    private com.toedter.calendar.JDateChooser fieldTMTJabatan;
    private javax.swing.JTextField fieldUnsurPenunjang;
    private javax.swing.JTextField fieldUnsurUtama;
    private javax.swing.JTextField fieldUnsurUtamaIjazah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelBagian;
    private javax.swing.JLabel labelBidang;
    private javax.swing.JLabel labelGol;
    private javax.swing.JLabel labelJabatan;
    private javax.swing.JLabel labelNIP;
    private javax.swing.JLabel labelNama;
    // End of variables declaration//GEN-END:variables
}
